mod part1;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
struct Coordinate {
    height: i32,
    width: i32,
}


pub fn solve_part1_example() -> usize{
    let input = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
.... .... .... ";

    part1::solve(input)
}

pub fn solve_part1() -> usize {
    let input = include_str!("../input.txt");

    part1::solve(input)
}